SET SQLBLANKLINES ON
CREATE TABLESPACE SYSAUX 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE SYSTEM 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT MANUAL 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TEMPORARY TABLESPACE TEMP 
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1048576;

CREATE UNDO TABLESPACE UNDO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
    RETENTION NOGUARANTEE;

CREATE TABLESPACE USERS 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLE CONTACTS 
(
  CONTACT_ID NUMBER NOT NULL 
, CONTACT_OWNER_ID NUMBER NOT NULL 
, CONTACT_OWNER_TYPE VARCHAR2(20 BYTE) NOT NULL 
, STREET1 VARCHAR2(200 BYTE) 
, STREET2 VARCHAR2(200 BYTE) 
, CITY VARCHAR2(20 BYTE) 
, STATE VARCHAR2(30 BYTE) 
, ZIP_CODE VARCHAR2(10 BYTE) 
, COUNTRY VARCHAR2(10 BYTE) 
, CONSTRAINT CONTACTS_PK PRIMARY KEY 
  (
    CONTACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTACTS_PK ON CONTACTS (CONTACT_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE CUSTOMERS 
(
  CUSTOMER_ID NUMBER NOT NULL 
, CUSTOMER_NAME VARCHAR2(100 BYTE) NOT NULL 
, CONTACT_NUMBER NUMBER 
, EMAIL_ID VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT CUSTOMERS_PK PRIMARY KEY 
  (
    CUSTOMER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CUSTOMERS_PK ON CUSTOMERS (CUSTOMER_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE EMPLOYEE 
(
  EMPLOYEE_ID NUMBER NOT NULL 
, FIRST_NAME VARCHAR2(100 BYTE) NOT NULL 
, MIDDLE_NAME VARCHAR2(100 BYTE) 
, LAST_NAME VARCHAR2(100 BYTE) 
, GENDER VARCHAR2(1 BYTE) NOT NULL 
, MARITAL_STATUS VARCHAR2(1 BYTE) 
, DOB DATE 
, SIGNATURE_FILE_ID NUMBER 
, PRIMARY_EMAIL VARCHAR2(100 BYTE) NOT NULL 
, WORK_EMAIL VARCHAR2(100 BYTE) 
, WORK_PHONE VARCHAR2(10 BYTE) 
, WORK_PHONE_EXT VARCHAR2(10 BYTE) 
, CELL_PHONE VARCHAR2(10 BYTE) 
, FAX VARCHAR2(10 BYTE) 
, PROFILE_PICTURE_FILE_ID NUMBER 
, CONSTRAINT EMPLOYEE_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLOYEE_PK ON EMPLOYEE (EMPLOYEE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE EMP_TASKS 
(
  EMP_ID NUMBER NOT NULL 
, TASK_ID NUMBER NOT NULL 
, CONSTRAINT EMP_TASKS_PK PRIMARY KEY 
  (
    EMP_ID 
  , TASK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMP_TASKS_PK ON EMP_TASKS (EMP_ID ASC, TASK_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE FILE_STORE 
(
  FILE_ID NUMBER NOT NULL 
, FILE_CONTENT_TYPE VARCHAR2(100 BYTE) NOT NULL 
, FILE_CONTENT BLOB 
, CONSTRAINT FILES_STORE_PK PRIMARY KEY 
  (
    FILE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX FILES_STORE_PK ON FILE_STORE (FILE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
LOB (FILE_CONTENT) STORE AS SYS_LOB0000014905C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  STORAGE 
  ( 
    INITIAL 65536 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE GROUPS 
(
  GROUP_ID NUMBER NOT NULL 
, GROUP_NAME VARCHAR2(20 BYTE) NOT NULL 
, GROUP_DESC VARCHAR2(200 BYTE) DEFAULT NULL 
, CONSTRAINT SYS_C004269 PRIMARY KEY 
  (
    GROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C004269 ON GROUPS (GROUP_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE HR_LOOKUPS 
(
  LOOKUP_ID NUMBER NOT NULL 
, LOOKUP_TYPE VARCHAR2(20 BYTE) NOT NULL 
, LOOKUP_VALUE VARCHAR2(20 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(50 BYTE) NOT NULL 
, ACTIVE_FLAG VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL 
, CONSTRAINT HR_LOOKUPS_PK PRIMARY KEY 
  (
    LOOKUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX HR_LOOKUPS_PK ON HR_LOOKUPS (LOOKUP_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE PS_TXN 
(
  ID NUMBER(20, 0) NOT NULL 
, PARENTID NUMBER(20, 0) 
, COLLID NUMBER(10, 0) NOT NULL 
, CONTENT BLOB 
, CREATION_DATE DATE DEFAULT sysdate 
, CONSTRAINT PS_TXN_PK PRIMARY KEY 
  (
    COLLID 
  , ID 
  )
  USING INDEX 
  (
      CREATE INDEX PS_TXN_IDX ON PS_TXN (COLLID ASC, ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
LOB (CONTENT) STORE AS SYS_LOB0000015007C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  CACHE 
  LOGGING 
  STORAGE 
  ( 
    INITIAL 65536 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE TASKS 
(
  TASK_ID NUMBER NOT NULL 
, CUSTOMER_ID NUMBER NOT NULL 
, TASK_NAME VARCHAR2(100 BYTE) NOT NULL 
, START_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) 
, CONSTRAINT TASKS_PK PRIMARY KEY 
  (
    TASK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TASKS_PK ON TASKS (TASK_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE TIME_ENTRY 
(
  TIME_ENTRY_ID NUMBER NOT NULL 
, EMP_ID NUMBER NOT NULL 
, TASK_ID NUMBER 
, TIME_ENTRY_DATE DATE 
, TIME_ENTRY_HOURS NUMBER 
, TIME_ENTRY_MINUTES NUMBER 
, TIME_ENTRY_STATUS NUMBER DEFAULT 1 
, TIME_ENTRY_COMMENTS VARCHAR2(200 BYTE) 
, CONSTRAINT TIME_ENTRY_PK PRIMARY KEY 
  (
    TIME_ENTRY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TIME_ENTRY_PK ON TIME_ENTRY (TIME_ENTRY_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE TIME_ENTRY_NOTES 
(
  NOTE_ID NUMBER NOT NULL 
, NOTE_WEEK_START_DATE DATE NOT NULL 
, EMP_ID NUMBER NOT NULL 
, NOTES VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT TIME_ENTRY_NOTES_PK PRIMARY KEY 
  (
    NOTE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TIME_ENTRY_NOTES_PK ON TIME_ENTRY_NOTES (NOTE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE USERS 
(
  USER_ID NUMBER NOT NULL 
, USERNAME VARCHAR2(10 BYTE) NOT NULL 
, PASSWORD VARCHAR2(64 BYTE) NOT NULL 
, EMPLOYEE_ID NUMBER 
, E_PASSWORD VARCHAR2(64 BYTE) 
, CONSTRAINT SYS_C004273 PRIMARY KEY 
  (
    USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C004273 ON USERS (USER_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE TABLE USER_GROUPS 
(
  USER_ID NUMBER NOT NULL 
, GROUP_ID NUMBER NOT NULL 
, CONSTRAINT SYS_C004276 PRIMARY KEY 
  (
    USER_ID 
  , GROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C004276 ON USER_GROUPS (USER_ID ASC, GROUP_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE VIEW HR_USERS_V
AS SELECT username, E_PASSWORD password    
FROM users;

CREATE VIEW HR_GROUPS_V
AS SELECT a.username username, b.group_name groupname
from USERS a, GROUPS b, USER_GROUPS c
where a.USER_ID = c.USER_ID and b.GROUP_ID = c.GROUP_ID;

CREATE UNIQUE INDEX CONTACTS_PK ON CONTACTS (CONTACT_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX CUSTOMERS_PK ON CUSTOMERS (CUSTOMER_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX EMPLOYEE_PK ON EMPLOYEE (EMPLOYEE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX EMP_TASKS_PK ON EMP_TASKS (EMP_ID ASC, TASK_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX FILES_STORE_PK ON FILE_STORE (FILE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX HR_LOOKUPS_PK ON HR_LOOKUPS (LOOKUP_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS_TXN_IDX ON PS_TXN (COLLID ASC, ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX SYS_C004269 ON GROUPS (GROUP_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX SYS_C004273 ON USERS (USER_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX SYS_C004276 ON USER_GROUPS (USER_ID ASC, GROUP_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX TASKS_PK ON TASKS (TASK_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX TIME_ENTRY_NOTES_PK ON TIME_ENTRY_NOTES (NOTE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX TIME_ENTRY_PK ON TIME_ENTRY (TIME_ENTRY_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE USER_GROUPS
ADD CONSTRAINT FK_GROUPS FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE USER_GROUPS
ADD CONSTRAINT FK_USERS FOREIGN KEY
(
  USER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ENABLE;

COMMENT ON COLUMN CONTACTS.CONTACT_OWNER_TYPE IS 'EMP OR COMPANT ETC';

COMMENT ON COLUMN HR_LOOKUPS.ACTIVE_FLAG IS 'Y FOR ACTIVE N FOR NOON ACTIVE';

CREATE SEQUENCE CUSTOMER_SEQ INCREMENT BY 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE FILE_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE LOOKUP_SEQ INCREMENT BY 1 MAXVALUE 9999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE NOTES_SEQ INCREMENT BY 1 MAXVALUE 999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE PS_TXN_SEQ INCREMENT BY 50 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE TASK_SEQ INCREMENT BY 1 MAXVALUE 9999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE TIME_ENTRY_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE USER_DTL_SEQ INCREMENT BY 1 MAXVALUE 99999999999999 MINVALUE 1 CACHE 20;
