package com.sd.motoraccreditation.model.admin.usermanagement.view;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 14 13:28:53 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserVORowImpl extends ViewRowImpl {
    public static final int ENTITY_USEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        Username,
        Password,
        EmployeeId,
        EPassword,
        UserGroupVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EPASSWORD = AttributesEnum.EPassword.index();
    public static final int USERGROUPVO = AttributesEnum.UserGroupVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UserVORowImpl() {
    }

    /**
     * Gets UserEO entity object.
     * @return the UserEO
     */
    public EntityImpl getUserEO() {
        return (EntityImpl) getEntity(ENTITY_USEREO);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USERNAME using the alias name Username.
     * @param value value to set the USERNAME
     */
    public void setUsername(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for PASSWORD using the alias name Password.
     * @return the PASSWORD
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD using the alias name Password.
     * @param value value to set the PASSWORD
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for E_PASSWORD using the alias name EPassword.
     * @return the E_PASSWORD
     */
    public String getEPassword() {
        return (String) getAttributeInternal(EPASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for E_PASSWORD using the alias name EPassword.
     * @param value value to set the E_PASSWORD
     */
    public void setEPassword(String value) {
        setAttributeInternal(EPASSWORD, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UserGroupVO.
     */
    public RowIterator getUserGroupVO() {
        return (RowIterator) getAttributeInternal(USERGROUPVO);
    }
    
    @Override
    public void setNewRowState(byte b) {
        if (b != Row.STATUS_INITIALIZED || getNewRowState() != Row.STATUS_NEW) {
            super.setNewRowState(b);
        }
    }
}

